version: '3.8'

services:
  backend:
    build: ./AuthApp
    container_name: netflix-backend
    ports:
      - "5000:5000"
    env_file:
      - ./AuthApp/.env
    restart: always

  frontend:
    build: ./netflix
    container_name: netflix-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: always

 
