version: '3.8'

services:
  backend:
    build: ./AuthApp
    ports:
      - "5000:5000"
    env_file:
      - ./AuthApp/.env
    restart: always

  frontend:
    build: ./netflix
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000   # use service name, not localhost
    depends_on:
      - backend
    restart: always

